Object.assign(module.exports, require('./core'))
Object.assign(module.exports, require('./location'))
Object.assign(module.exports, require('./movement'))
Object.assign(module.exports, require('./actions'))
Object.assign(module.exports, require('./sound'))
Object.assign(module.exports, require('./fashion'))
Object.assign(module.exports, require('./walk'))
Object.assign(module.exports, require('./food'))
Object.assign(module.exports, require('./experimental'))
Object.assign(module.exports, require('./emotion'))
Object.assign(module.exports, require('./easter-eggs'))
Object.assign(module.exports, require('./smoking'))

module.exports.goTo = require('./goTo')
module.exports.Approach = require('./Approach')
